# Pentagonal numbers are generated by the formula, Pn=n(3n - 1)/2. The first ten
# pentagonal numbers are:

#         1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
# 70 - 22 = 48, is not pentagonal.

# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
# difference is pentagonal and D = |Pk - Pj| is minimised; what is the value of
# D?

require 'pp'

$pentagonals_a = []
$pentagonals_h = {}

def generate_pentagonals(max_n)
  1.upto(max_n) do |n|
    t = n * ((3 * n) - 1)/2
    $pentagonals_a << t
    $pentagonals_h[t] = true
  end
end

generate_pentagonals(10_000)

d = nil

$pentagonals_a.each_with_index do |pj, index|
  $pentagonals_a[index..$pentagonals_a.length].each do |pk|
    difference = pk - pj
    next unless $pentagonals_h[difference]
    sum = pj + pk
    if $pentagonals_h[sum] then
      puts "FOUND #{pk} #{pj} Difference #{difference} Sum #{sum}"
      d = difference
      break
    end
  end
  break if d
end

puts "D #{d}"

# time ruby pentagonal.rb
# FOUND 7042750 1560090 Difference 5482660 Sum 8602840
# D 5482660

# real	0m8.868s
# user	0m8.637s
# sys	0m0.016s
